### ISSUE TITLE
xml template

### ISSUE THREAD

**Issue by Anniepoo** [rla/simple-template#13]
I have svg files I'm inserting content in (you can imagine what the project is ;-)  ) 

I'm having to lie that the svg files are html to get simple_template to take them. is there a way to retain the original .svg extension?

**Comment by rla** [comment]
Not at the moment. template settings are global.

**Comment by rla** [comment]
I can implement this in a week. st_render_ predicates need options data that will contain the extension name. When the extension name is missing then global value will be used.

**Comment by rla** [comment]
Global settings are now removed and different filename extensions can be used. README contains the new API description.
