### ISSUE TITLE
Templating Syntax Collision

### ISSUE THREAD

**Issue by jlturner** [rla/simple-template#18]
I've run into an issue using templates to create templates for some golang based templating languages. I'm proposing a way to define the syntax delimiters used for templating through `simple-template`.

**Comment by jlturner** [comment]
I've linked a PR that allows for extensible syntax that I've been using for this. I've added tests to the suite, and the original two syntaxes are defined using it and pass the existing test suite.
https://github.com/rla/simple-template/pull/17

**Comment by rla** [comment]
@jlturner, thanks! The PR is really useful. I had an idea to do something like this when the Semblance syntax was pushed but I did not find a good way to structure configuration for it. I'm going to merge and publish a new version of the pack asap.

**Comment by jlturner** [comment]
@rla Of course, glad you like it. Thanks for maintaining the package and getting back so quick! Look forward to the new version (and getting rid of the gross submodule to my fork & branch lol). Feel free to close the issue & PR after merge / deploy.

**Comment by rla** [comment]
Merged and published.
